config/routes.rb
Rails.application.routes.draw do
  root "lists#index"



  resources :lists do
    resources :tasks
  end
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
    devise_scope :users do
      get '/users/sign_out' => 'devise/sessions#destroy'
    end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
    has_many :tasks
    has_many :user_lists
    validates_presence_of :name
    validates :name, length: { minimum: 2 }, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :list
    validates_presence_of :name
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true
  validates :password, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

      devise :omniauthable, :omniauth_providers => [:facebook]

    has_many :user_lists
    has_many :lists, through: :user_lists
    has_many :tasks, through: :lists

    def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
      end 
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    def after_sign_in_path_for(resource)
        request.env['omniauth.origin'] || root_path
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

    def index
        @list = List.new
        @lists = List.all
    end

    def show
        @list = List.find(params[:id])
        @task = Task.new
    end

    def new
        @list = current_user.list.new
        @list.tasks.build
    end

    def create
        @list = current_user.lists.new(list_params)
        if @list.save
            @user_list = UserList.create(list_id: @list.id, user_id: current_user.id)
            redirect_to @list
        else
            @error = @list.errors.full_messages
            render :new
        end
    end


    def destroy
        @list = current_user.lists.find(params[:id])
        @list.destroy
        redirect_to @list
    end
    
    private

    def list_params
        params.require(:list).permit(:name, tasks_attributes: [:name])
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

    def index
        @task = Task.all
    end
    
    def show
    end

    def create
        @list = current_user.lists.find(params[:list_id])
        @task = @list.tasks.build(task_params)
        if @task.valid?
            @task.save
            redirect_to @list
        else
            @error = @task.errors.full_messages
            render :new
        end
    end

    def edit
        @task = Task.find(params[:id])
        render :edit
    end

    def update
        @task = Task.find(params[:id])
        @task.update(task_params)
        if @task.valid?
            @task.save
            redirect_to list_path(@task.list)
        else
            @error = @task.errors.full_messages
            render :edit
        end
    end
    

    def destroy
        @list = current_user.lists.find(params[:list_id])
        @task = @list.tasks.find(params[:id])
        @task.destroy
        redirect_to list_path(@task.list)
    end

    private

    def task_params
        params.require(:task).permit(:name)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def facebook
      @user = User.from_omniauth(request.env["omniauth.auth"])
      if @user.persisted?
        sign_in_and_redirect @user
      else
        redirect_to new_user_registration_path
      end       
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ListTaskManager</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" integrity="sha384-y3tfxAZXuh4HwSYylfB+J125MxIs6mR5FOHamPBG064zB+AFeWH94NdvaCBm8qnd" crossorigin="anonymous">
    <%= stylesheet_link_tag "application.css" %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    

    <nav class="navbar navbar-expand-md navbar-light" style="background-color: #FFFFFF;">
        <a class="navbar-brand" <%= link_to "List Manager", new_user_session_path, method: :get %></a>
          <div class="navbar-nav">
              <a class="nav-item nav-link active" </a>
              <a class="nav-item nav-link" <%= link_to "Login", new_user_session_path, method: :get %></a>
              <a class="nav-item nav-link" <%= link_to "Signup", new_user_registration_path, method: :get %></a>
              <a class="nav-item nav-link" <%= link_to "Lists", root_path, method: :get %></a>
              <a class="nav-item nav-link"> <%= button_to "logout", destroy_user_session_path, method: :delete  %></a>
            </div>
          </div>
    </nav>


    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  </head>

  <body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>





  <div class="wrapper">

    
    <%= yield %>

    <footer class="branding">
        <small>&copy; 2021 <strong>List/Task Manager</strong></small>
    </footer>

  </div>

    


  </body>
</html>

app/views/lists/_list.html.erb
<ul><%= form_for(@list) do |list_form| %>
   <% if @list.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

            <ul>
            <% @list.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
    <ul> <h4>List Name: <%= list_form.text_field :name, placeholder: "Create a List" %></h4>
       <%= list_form.fields_for :tasks, @list.tasks do |task_field| %>
         <h4>Task Name: <%= task_field.text_field :name, placeholder: "Create a Task" %></h4>
       <% end %>
       <h4><%= list_form.submit %></h4>
    <% end %>
   </ul>
</ul>

app/views/lists/edit.html.erb
<h2>Edit Your List:</h2>
<h3><%= @list.name %></h3>

<%= render 'list' %>

app/views/lists/index.html.erb
<div class="container">
<% if user_signed_in? %> 
  <h2><ul> Welcome, <%= current_user.email if !current_user.nil? %></ul></h2>
    

    <div class="inline">
    <ul><%= form_for @list, :html => {:class => "form-horizontal center"} do |f| %>
      <% if @list.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

            <ul>
            <% @list.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
      <div class="form-group">
      <%= f.text_field :name, placeholder: 'i.e. Grocery', class: "form-control" %>
      <%= f.submit class: 'btn btn-primary' %>
      </div>
      <% end %>
    </ul>
    </div>
    
    

    <ul><h2>Here are all lists:</h2>
      <% @lists.each do |list| %>
        <div class="card mb-3">
        <div class="card-body">
        <div class="d-flex justify-content-between">
          <ul><h2><%= list.name %></h2></ul>
        <div>
        <a class="card-link"><%= button_to "Delete", list_path(list), :method => "delete", :class => 'btn btn-dark btn-sm btn btn-danger' %>
        <a class="card-link"><%= button_to "view", list_path(list), :method => "get", :class => 'btn btn-dark btn-sm btn btn-warning' %>
        </div>
          </div>
        </div>
      </div>
      <% end %>
    </ul>


<% else %>
  <h2><ul> Welcome!</ul></h2>
  <ul><h3>This is a List task manager application for users to keep track of their daily functions.</h3></ul>
  <ul><h3>To get started, click the menu icon and click "Sign Up" - or "Login" if you've already made an account.</h3></ul>
  <ul><h4>(You may also be given the option to sign in with your Facebook info if you'd prefer.)</h4></ul>
<% end %>
</div>

app/views/lists/new.html.erb
<ul><h2>Whoops that didn't work</h2>

<% if @list.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

            <ul>
            <% @list.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
<% end %>
<br>

<%= form_for @list do |f| %>
    <%= f.text_field :name, placeholder: 'i.e. Name of list', class: "form-control" %>
    <%= f.submit class: 'btn btn-primary' %>
    <% end %>



<%= link_to 'Back', lists_path, class: 'btn btn-secondary mb-3' %>

app/views/lists/show.html.erb
<%= link_to 'Back', lists_path, class: 'btn btn-secondary mb-3' %>
<div class="container">
<ul>
  <h2><%= @list.name %></h2>
    <%= form_for [@list, Task.new], :html => {:class => "form-horizontal center"} do |f| %>
      <%= f.hidden_field :status, value: 'not-started' %>
      <div class="form-group">
      <%= f.text_field :name, class: "form-control", placeholder: "Create a task" %>
      <%= f. submit class: 'btn btn-primary' %>
      </div>
    <% end %>

    


  <h2>Here are all of the tasks:</h2>
    <% @list.tasks.each do |task| %>
      <div class="card mb-3">
      <div class="card-body">
        <div class="d-flex justify-content-between">
          <ul><h2><%= task.name %></h2></ul>
            <div>
            <a class="card-link"><%= button_to 'Delete', list_task_path(task.list, task), method: :delete, class: 'btn btn-dark btn-sm btn-danger' %></a>
            <a class="card-link"><%= button_to 'Edit', edit_list_task_path(task.list, task), method: :get, class: 'btn btn-dark btn-sm btn-info' %></a>
            </div>
          </div>
        </div>
      </div>
    <% end %>
</ul>
</div>

app/views/tasks/_task.html.erb
<label>
    <%= task.name %>
</label>

app/views/tasks/edit.html.erb
<h2>Edit Your Task:</h2>
<h1><strong><%= @task.name %></strong></h1>
<% if @task.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@task.errors.count, "error") %> prohibited this Task from being Edited:</h2>

            <ul>
            <% @task.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

<%= form_with(model: @task, url: list_task_path, method: "patch") do |f| %>
  <%= f.text_field :name, placeholder: 'i.e. Grocery', class: "form-control" %>
  <%= f.submit class: 'btn btn-primary' %>
  </div>
  <% end %>

app/views/tasks/index.html.erb
<h2>Here are all of the tasks:</h2>
<% @task.each do |task| %>
    <h2>
        <ul>
            > <%= task.name %>
            <ul>
                <h4>
                    <%= button_to "Task complete?", list_task_path(task.list, task), :method => "delete", :class => "destroy" %>
                </h4>
            </ul>
        </ul>
    </h2>
<% end %>

app/views/tasks/new.html.erb
<ul><h2>Whoops that didn't work</h2>

<% if @task.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

            <ul>
            <% @task.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
<% end %>
<br>

<%= form_for [@list, Task.new] do |f| %>
    <%= f.text_field :name, placeholder: 'i.e. Name of Task', class: "form-control" %>
    <%= f.submit class: 'btn btn-primary' %>
    <% end %>



<%= link_to 'Back', lists_path, class: 'btn btn-secondary mb-3' %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with Facebook", omniauth_authorize_path(resource_name, provider), class: 'btn btn-dark btn-sm btn-primary'  %><br />
  <% end %>
<% end %>